### ISSUE TITLE
Failed to read .tours/ directory

### ISSUE THREAD

**Issue by NxSoftware** [pozil/codetour-watch#4]
The action is failing to find the `.tours` directory either when using the default `tour-path` option, or explicitly setting it:

```
Error: Failed to read .tours/ directory: Error: ENOENT: no such file or directory, scandir '.tours/'
     at loadCodetours (/home/runner/work/_actions/pozil/codetour-watch/v1.2.0/src/index.js:209:15)
```

Do I need to use the [checkout action](https://github.com/actions/checkout) in conjunction with this action?

Here is my YAML file:

```yaml
name: CodeTour Watch
on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: CodeTour
        uses: pozil/codetour-watch@v1.2.0
        with:
          repo-token: ***REDACTED***
```
